name: Build Android ANPR App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip git zip unzip openjdk-8-jdk
        sudo apt-get install -y autoconf=2.69-11 libtool=2.4.6-14 pkg-config zlib1g-dev
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5
        sudo apt-get install -y cmake libffi-dev libssl-dev
        sudo apt-get install -y build-essential
        
    - name: Install Python dependencies
      run: |
        pip3 install buildozer cython
        
    - name: Set environment variables
      run: |
        echo "BUILD_DIR=/tmp/buildozer" >> $GITHUB_ENV
        echo "PYTHONPATH=/tmp/buildozer" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        buildozer android debug
      env:
        BUILD_DIR: /tmp/buildozer
        PYTHONPATH: /tmp/buildozer
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: anpr-app-apk
        path: bin/*.apk

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer/
